
version: 2

models:
  - name: int_district_settings
    description: >
      Purpose: Parse the JSON related to district settings.
      Granularity: One row per district.
      Filters include: `district_settings` is not null
    columns:
      - name: district_id
        tests: 
          - not_null
          - unique
        description: "{{ doc('district_id') }}"
      - name: district_grades
        description: "{{ doc('district_grades') }}"
      - name: rostering_method
        description: "{{ doc('rostering_method') }}"
      - name: rostering_classlink_id
        description: "{{ doc('rostering_classlink_id') }}"
      - name: rostering_clever_id
        description: "{{ doc('rostering_clever_id') }}"
      - name: rostering_upload_method
        description: "{{ doc('rostering_upload_method') }}"
      - name: rostering_rostering_type
        description: "{{ doc('rostering_rostering_type') }}"
      - name: rostering_state_id_field
        description: "{{ doc('rostering_state_id_field') }}"
      - name: rostering_is_active_send_invite
        description: "{{ doc('rostering_is_active_send_invite') }}"
      - name: is_rostering_allow_users_without_class_or_school
        description: "{{ doc('is_rostering_allow_users_without_class_or_school') }}"
      - name: is_selfservice_rostering_show_clever
        description: "{{ doc('is_selfservice_rostering_show_clever') }}"
      - name: is_selfservice_authentication_show_clever
        description: "{{ doc('is_selfservice_authentication_show_clever') }}"
      - name: authentication_provider
        description: "{{ doc('authentication_provider') }}"
      - name: authentication_login_field
        description: "{{ doc('authentication_login_field') }}"
      - name: authentication_classlink_settings_classlink_id
        description: "{{ doc('authentication_classlink_settings_classlink_id') }}"
      - name: authentication_clever_settings_clever_id
        description: "{{ doc('authentication_clever_settings_clever_id') }}"
      - name: authentication_clever_settings_provider_name
        description: "{{ doc('authentication_clever_settings_provider_name') }}"
      - name: authentication_saml_settings_provider_name
        description: "{{ doc('authentication_saml_settings_provider_name') }}"
      - name: authentication_saml_settings_metadata_document_file
        description: "{{ doc('authentication_saml_settings_metadata_document_file') }}"
      - name: authentication_saml_settings_metadata_document_source
        description: "{{ doc('authentication_saml_settings_metadata_document_source') }}"
      - name: is_onboarding_required
        description: "{{ doc('is_onboarding_required') }}"
      - name: user_pool_client_id
        description: "{{ doc('user_pool_client_id') }}"