
version: 2

models:
  - name: int_districts_history_parse_settings
    description: |
      Purpose: Parses district settings from JSON to structured columns including rostering, authentication, and onboarding configurations.
      Granularity: One row per district.
      Filters: Picks the snapshot record with `dbt_valid_to` is null
    columns:
      - name: dbt_scd_id
        tests:
          - unique
          - not_null
      - name: district_id
        description: "{{ doc('district_id') }}"
      - name: district_settings
        description: "{{ doc('district_settings') }}"
      - name: dbt_valid_from
        description: "{{ doc('dbt_valid_from') }}"
      - name: dbt_valid_to
        description: "{{ doc('dbt_valid_to') }}"
      - name: dbt_is_deleted
        description: "{{ doc('dbt_is_deleted') }}"
      - name: district_grades
        description: "{{ doc('district_grades') }}"
      - name: rostering_method
        description: "{{ doc('rostering_method') }}"
      - name: rostering_upload_method
        description: "{{ doc('rostering_upload_method') }}"
      - name: rostering_rostering_type
        description: "{{ doc('rostering_rostering_type') }}"
      - name: rostering_state_id_field
        description: "{{ doc('rostering_state_id_field') }}"
      - name: is_rostering_allow_users_without_class_or_school
        description: "{{ doc('is_rostering_allow_users_without_class_or_school') }}"
      - name: is_selfservice_rostering_show_clever
        description: "{{ doc('is_selfservice_rostering_show_clever') }}"
      - name: is_selfservice_authentication_show_clever
        description: "{{ doc('is_selfservice_authentication_show_clever') }}"
      - name: authentication_provider
        description: "{{ doc('authentication_provider') }}"
      - name: authentication_classlink_settings_classlink_id
        description: "{{ doc('authentication_classlink_settings_classlink_id') }}"
      - name: authentication_clever_settings_clever_id
        description: "{{ doc('authentication_clever_settings_clever_id') }}"
      - name: authentication_clever_settings_provider_name
        description: "{{ doc('authentication_clever_settings_provider_name') }}"
      - name: authentication_saml_settings_provider_name
        description: "{{ doc('authentication_saml_settings_provider_name') }}"
      - name: authentication_saml_settings_metadata_document_source
        description: "{{ doc('authentication_saml_settings_metadata_document_source') }}"
      - name: is_onboarding_required
        description: "{{ doc('is_onboarding_required') }}"
      - name: user_pool_client_id
        description: "{{ doc('user_pool_client_id') }}"