version: 2

models:
  - name: dim_applications
    description: |
      Purpose: Third-party applications data.
      Granularity: One row per application, defined by `application_id`.
    columns:
      - name: application_id
        tests:
          - unique
          - not_null