version: 2

snapshots:
  - name: snp_taco__district_applications
    relation: source('taco', 'raw_taco__district_applications')
    config:
      unique_key: id
      strategy: check
      check_cols: 'all'
      hard_deletes: 'new_record'
      dbt_valid_to_current:  "{{ var('dbt_valid_to_current') }}"