version: 2

models:
  - name: stg_taco__district_application_licenses
    description: |
      Purpose: Tracks quantity and expiration dates for districts' third-party application licenses.
      Granularity: One row per district application license.
    columns:
      # source tests for unique district_application_license_id
      - name: district_application_license_id
        data_tests:
          - not_null
          - unique
      - name: district_id
        description: "{{ doc('district_id') }}"
      - name: license_start_date
        description: "{{ doc('license_start_date') }}"
      - name: updated_at_utc
        description: "{{ doc('updated_at_utc') }}"
